name: Frontend CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash
    working-directory: frontend/

jobs:
  ci:
    name: Lint, build and test frontend
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 18.12.0

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.5.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn install
        working-directory: frontend/frontend/

      - name: Lint project
        run: yarn lint
        working-directory: frontend/frontend/

      - name: Test project
        run: yarn test
        working-directory: frontend/frontend/
